[Interface]
Address = <SERVER_VPN_IP>
ListenPort = 51820
PrivateKey = <SERVER_PRIVATE_KEY>

# NAT / routing rules
PostUp = iptables -I FORWARD -i wg0 -j ACCEPT
PostUp = iptables -I FORWARD -o wg0 -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o <HOST_INTERFACE> -j MASQUERADE

PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o <HOST_INTERFACE> -j MASQUERADE

[Peer]
PublicKey = <CLIENT1_PUBLIC_KEY>
AllowedIPs = <CLIENT1_VPN_IP>

[Peer]
PublicKey = <CLIENT2_PUBLIC_KEY>
AllowedIPs = <CLIENT2_VPN_IP>

[Peer]
PublicKey = <CLIENT3_PUBLIC_KEY>
AllowedIPs = <CLIENT3_VPN_IP>